# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Soul' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Soul
  # add the Firebase pod for Google Analytics
  pod 'Firebase'
  pod 'Firebase/Auth' 
  # add pods for any other desired Firebase products 
  # https://firebase.google.com/docs/ios/setup#available-pods

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
        configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        configuration.build_settings.delete('ARCHS')
        configuration.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
       end
   end
end
